# Q3 Using Scikit-Learn

In [1]:
import numpy as np
import pandas as pd
import time
import gc

from sklearn.model_selection import cross_val_score, GridSearchCV, cross_validate, train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, normalize
from sklearn.decomposition import PCA
# Import statements run before running other code cells

# Classifier Setup

In [2]:
# XXX
# TODO: Read in all the data. Replace the 'xxx' with the path to the data set.
# XXX

# data = pd.read_csv('xxx')

# Separate out the x_data and y_data.
# x_data = data.loc[:, data.columns != "y"]
# y_data = data.loc[:, "y"]

# -------------------------------
data = pd.read_csv('pulsar_stars.csv')

# Separate out the x_data and y_data.
x_data = data.loc[:, data.columns != "y"]
y_data = data.loc[:, "y"]
# -------------------------------

In [3]:
# The random state to use while splitting the data.
# random_state = 100

# XXX
# TODO: Split 70% of the data into training and 30% into test sets. Call them x_train, x_test, y_train and y_test.
# Use the train_test_split method in sklearn with the parameter 'shuffle' set to true and the 'random_state' set to 100.
# XXX

# -------------------------------
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.3, random_state=100)
# -------------------------------

In [6]:
y_train

7078     0
10660    0
9635     0
9144     0
3570     0
        ..
16304    0
79       0
12119    0
14147    0
5640     0
Name: y, Length: 12528, dtype: int64

In [4]:
x_train

X1         X2        X3        X4          X5         X6  \
7078   114.734375  45.543675  0.229792  0.200990   24.144649  69.262865   
10660  109.351562  38.869893  0.168128  0.824654    1.384615  12.436564   
9635   106.109375  42.514930  0.537584  0.965991    2.300167  17.121229   
9144   129.070312  51.580214  0.227924 -0.025761    5.892977  26.877934   
3570    93.273438  51.757203  0.742549  0.474389  187.474080  60.763208   
...           ...        ...       ...       ...         ...        ...   
16304  107.453125  52.730129  0.480646 -0.080883  196.711538  69.991086   
79     124.500000  57.353618 -0.014849 -0.550964    4.783445  27.501640   
12119  105.875000  41.837110  0.253195  0.400189    2.087793  16.906634   
14147  109.906250  43.760255  0.053946  0.527836    5.914716  30.644925   
5640   119.500000  45.219430  0.166401  0.395791    1.078595  12.914065   

              X7          X8  
7078    2.531836    4.449188  
10660  12.255024  189.452922  
9635    9.246154   97.825740  
9144    5.328182   30.635998  
3570   -2.269474    4.231114  
...          ...         ...  
16304  -1.929495    2.532311  
79      6.090449   37.818091  
12119  10.166011  116.735237  
14147   5.802776   34.437668  
5640   14.790376  241.724271  

[12528 rows x 8 columns]

# Linear Regression 

In [9]:
# XXX
# TODO: Create a LinearRegression classifier and train it.
# XXX

# -------------------------------
reg = LinearRegression().fit(x_train, y_train)
# -------------------------------

In [23]:
# XXX
# TODO: Test its accuracy (on the training set) using the accuracy_score method.
# Note: Round the output values greater than or equal to 0.5 to 1 and those less than 0.5 to 0. You can use any method that satisfies the requriements.
# XXX

# -------------------------------
y_train_pred = [1 if i >=0.5 else 0 for i in reg.predict(x_train)]
accuracy_score(y_train, y_train_pred)
# -------------------------------

0.970705619412516

In [25]:
# XXX
# TODO: Test its accuracy (on the testing set) using the accuracy_score method.
# Note: Round the output values greater than or equal to 0.5 to 1 and those less than 0.5 to 0. You can use any method that satisfies the requriements.
# XXX

# -------------------------------
y_test_pred = [1 if i >=0.5 else 0 for i in reg.predict(x_test)]
accuracy_score(y_test, y_test_pred)
# -------------------------------

0.9720670391061452

# Random Forest Classifier

In [26]:
# XXX
# TODO: Create a RandomForestClassifier and train it.
# WARNING: Ignore "FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22."10 in version 0.20 to 100 in 0.22."
# XXX

# -------------------------------
clf = RandomForestClassifier(n_estimators=100, max_depth=2,random_state=0)
clf.fit(x_train, y_train) 
# -------------------------------

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=2, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [30]:
# XXX
# TODO: Test its accuracy on the training set using the accuracy_score method.
# XXX

# -------------------------------
y_train_pred = clf.predict(x_train)
accuracy_score(y_train, y_train_pred)
# -------------------------------

0.9764527458492975

In [31]:
# XXX
# TODO: Test its accuracy on the test set using the accuracy_score method.
# XXX

# -------------------------------
y_test_pred = clf.predict(x_test)
accuracy_score(y_test, y_test_pred)
# -------------------------------

0.978584729981378

## Feature Importance

In [32]:
# XXX
# TODO: Determine and print the feature importance as evaluated by the Random Forest Classifier.
# XXX

# -------------------------------
clf.feature_importances_
# -------------------------------

array([0.19377698, 0.0342601 , 0.42766404, 0.15927066, 0.07075575,
       0.0775325 , 0.02846674, 0.00827322])

In [34]:
# XXX
# TODO: Sort them in the descending order and print the feature numbers[0 to ...].
#       Hint: There is a direct function available in sklearn to achieve this. Also checkout argsort() function in Python.
# XXX

# -------------------------------
np.argsort(-clf.feature_importances_)
# -------------------------------

array([2, 0, 3, 5, 4, 1, 6, 7], dtype=int64)

## Hyper-parameter Tuning

In [39]:
# XXX
# TODO: Tune the hyper-parameters 'n_estimators' and 'max_depth'.
# XXX

# -------------------------------
clf = RandomForestClassifier(n_estimators=100, max_depth=2,random_state=0)
n_list = [10,30,90,270]
depth_list = [3,10,30,None]
param_grid = {
    'n_estimators': n_list,
    'max_depth':depth_list
}
clf_tuned = GridSearchCV(estimator=clf, param_grid=param_grid)
clf_tuned.fit(x_train, y_train)
# -------------------------------

C:\Users\ZheMin\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=2,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False, random_state=0,
                                              verbose=0, warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'ma

In [40]:
# XXX
# TODO: Print the best params, using .best_params_
# XXX

# -------------------------------
clf_tuned.best_params_
# -------------------------------

{'max_depth': 10, 'n_estimators': 90}

In [41]:
# XXX
# TODO: Print the best score, using .best_score_.
# XXX

# -------------------------------
clf_tuned.best_score_
# -------------------------------

0.979565772669221

# Support Vector Machine

## Pre-process

In [46]:
# XXX
# TODO: Pre-process the data to standardize or normalize it, otherwise the grid search will take much longer.
# Warning: Ignore "FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning"
# XXX

# -------------------------------
scaler = StandardScaler()
scaler.fit(x_train)
x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)
# -------------------------------

In [49]:
# XXX
# TODO: Create a SVC classifier and train it.
# XXX

# -------------------------------
svm = SVC(gamma='auto')
svm.fit(x_train_scaled, y_train)
# -------------------------------

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [50]:
# XXX
# TODO: Test its accuracy on the training set using the accuracy_score method.
# XXX
# WARNING: Ignore "FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.""

# -------------------------------
y_train_pred = svm.predict(x_train_scaled)
accuracy_score(y_train, y_train_pred)
# -------------------------------

0.978448275862069

In [51]:
# XXX
# TODO: Test its accuracy on the test set using the accuracy_score method.
# XXX
# WARNING: Ignore "FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.""

# -------------------------------
y_test_pred = svm.predict(x_test_scaled)
accuracy_score(y_test, y_test_pred)
# -------------------------------

0.9797020484171323

## Hyper-parameter Tuning

In [52]:
# XXX
# TODO: Tune the hyper-parameters 'C' and 'kernel' (use rbf and linear).
# XXX

# -------------------------------
svm = SVC(gamma='auto')
C_list = [0.1,0.3,1.0,3.0,10.0]
kernel_list = ['linear','rbf']
param_grid = {
    'C': C_list,
    'kernel':kernel_list
}
svm_tuned = GridSearchCV(estimator=svm, param_grid=param_grid)
svm_tuned.fit(x_train_scaled, y_train)
# -------------------------------

C:\Users\ZheMin\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.1, 0.3, 1.0, 3.0, 10.0],
                         'kernel': ['linear', 'rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [55]:
# XXX
# TODO: Print the best score, using .best_score_.
# XXX

# -------------------------------
svm_tuned.best_score_
# -------------------------------

0.979007024265645

In [56]:
# XXX
# TODO: Get the training and test set accuracy values after hyperparameter tuning.
# XXX

# -------------------------------
y_train_pred = svm_tuned.predict(x_train_scaled)
y_test_pred = svm_tuned.predict(x_test_scaled)
# print("training accuracy:",accuracy_score(y_train, y_train_pred))
# print("test accuracy:",accuracy_score(y_test, y_test_pred))
# -------------------------------

training accuracy: 0.9806034482758621
test accuracy: 0.9813780260707635


In [59]:
# XXX
# TODO: Test its accuracy (on the training set) using the accuracy_score method.
# Note: Round the output values greater than or equal to 0.5 to 1 and those less than 0.5 to 0. You can use any method that satisfies the requriements.
# XXX

# -------------------------------
print(accuracy_score(y_train, y_train_pred))
# -------------------------------

0.9806034482758621


In [60]:
# XXX
# TODO: Test its accuracy (on the testing set) using the accuracy_score method.
# Note: Round the output values greater than or equal to 0.5 to 1 and those less than 0.5 to 0. You can use any method that satisfies the requriements.
# XXX

# -------------------------------
print(accuracy_score(y_test, y_test_pred))
# -------------------------------

0.9813780260707635


In [75]:
# XXX
# TODO: Calculate the rank test score, mean testing score and mean fit time for the 
# best combination of hyperparameter values that you obtained in Q3.2. The GridSearchCV 
# class holds a  ‘cv_results_’ dictionary that should help you report these metrics easily.
# XXX

# -------------------------------
res = svm_tuned.cv_results_
idx = svm_tuned.best_index_
res.keys()
# -------------------------------

dict_keys(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time', 'param_C', 'param_kernel', 'params', 'split0_test_score', 'split1_test_score', 'split2_test_score', 'mean_test_score', 'std_test_score', 'rank_test_score'])

In [78]:
# XXX
# TODO: Print the rank test score for the best combination of hyperparameter values that you obtained in Q3.2. The 
# GridSearchCV class holds a  ‘cv_results_’ dictionary that should help you report these metrics easily.
# XXX

# -------------------------------
res['rank_test_score'][idx]
# -------------------------------

1

In [79]:
# XXX
# TODO: Print mean testing score for the best combination of hyperparameter values that you obtained in Q3.2. The 
# GridSearchCV class holds a  ‘cv_results_’ dictionary that should help you report these metrics easily.
# XXX

# -------------------------------
res['mean_test_score'][idx]
# -------------------------------

0.979007024265645

In [80]:
# XXX
# TODO: Print mean fit time for the best combination of hyperparameter values that you obtained in Q3.2. The 
# GridSearchCV class holds a  ‘cv_results_’ dictionary that should help you report these metrics easily.
# XXX

# -------------------------------
res['mean_fit_time'][idx]
# -------------------------------

0.18315466245015463

# PCA

In [81]:
# XXX
# TODO: Perform dimensionality reduction of the data using PCA.
#       Set parameters n_component to 8 and svd_solver to 'full'. Keep other parameters at their default value.
# XXX

# -------------------------------
pca = PCA(n_components=8, svd_solver = 'full')
pca.fit(x_train)
# -------------------------------

PCA(copy=True, iterated_power='auto', n_components=8, random_state=None,
    svd_solver='full', tol=0.0, whiten=False)

In [84]:
# XXX
# TODO: Print Percentage of variance explained by each of the selected components
# XXX

# -------------------------------
pca.explained_variance_ratio_
# -------------------------------

array([8.71054855e-01, 7.80404050e-02, 4.12747422e-02, 6.15520409e-03,
       2.45425694e-03, 9.78533643e-04, 3.91429289e-05, 2.85984066e-06])

In [85]:
# XXX
# TODO: The singular values corresponding to each of the selected components.
# XXX

# -------------------------------
pca.singular_values_
# -------------------------------

array([11992.97512747,  3589.74779466,  2610.63625426,  1008.15059028,
         636.59642313,   401.9685368 ,    80.39533321,    21.73076915])